name: Bug Report
description: Report a problem with care.nvim
title: "bug: "
labels: [bug]
body:
  - type: checkboxes
    id: faq-prerequisite
    attributes:
      label: Prerequisites
      options:
        - label: I am using the latest stable neovim version
          required: true
        - label: I am using the latest version of the plugin
          required: true
  - type: input
    attributes:
      label: "Neovim Version"
      description: "`nvim --version`:"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "care.nvim setup"
      description: |
        - Copy your entire `require("care").setup` function
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Actual behavior"
      description: "A description of actual behavior. May optionally include images or videos."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Expected behavior"
      description: "A description of the behavior you expected."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Healthcheck"
      description: "Output of `:checkhealth care`"
      render: markdown
      placeholder: |
        care: require("care.health").check()
        ========================================================================
        ## care.nvim
  - type: textarea
    attributes:
      label: "Steps to reproduce"
      description: "Please describe how we can reproduce the issue."
      placeholder: |
        1. `nvim -nu minimal.lua`
        2. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Other information"
      description: "Other information that could be helpful with debugging."
  - type: textarea
    attributes:
      label: "Minimal config"
      description: "Minimal config with which the issue is reproducible. Save this as `minimal_init.lua. Add plugins and configs which are necessary at indicated location."
      render: Lua
      placeholder: |
        -- See minimal_init.lua in repository root
    validations:
      required: true
